-
  deploy:
    RelayWithBulkStore:
      contract: ../btcBulkStoreHeaders.se
      gas: 3100000
      wait: True

# token contracts are on private testnet
# NOTE initTokenContract requires the address of the TokenFactory
# must also ensure enough gas!
# -
#   transact:
#     initTokenContract:
#       gas: 1200000
#       to: $RelayWithBulkStore
#       sig: initTokenContract:[int256]:int256
#       data:
#         - 0x55a285c6f02fcb7ba51c44d5a019153d8e39390e
#       retry: 60
#       wait: True

# parent block is Bitcoin Livenet
-
  transact:
    SetInitialParent:
      gas: 150000
      to: $RelayWithBulkStore
      sig: setInitialParent:[int256,int256,int256]:int256
      data:
        - 0x0000000000000000034656c96781091b5fbc799c881ea85b41cba0b88128eff7
        - 405215  # make sure this follows rules of SetInitialParent()
        - 25595175441092480474092128  # use test/script/chainwork.py or https://chainquery.com/bitcoin-api/getblock
      retry: 60
      wait: True
