-
  deploy:
    RelayWithBulkStore:
      contract: ../btcBulkStoreHeaders.se
      gas: 3000000
      wait: True

# Livenet
-
  transact:
    SetInitialParent:
      gas: 150000
      to: $RelayWithBulkStore
      sig: setInitialParent:[int256,int256,int256]:int256
      data:
        - 0x00000000000000000d26d1ec7eee34b726fba0d4d776392dae0b9cb960a1ddb3
        - 375948
        - 1
      retry: 60
      wait: True
