-
  set:
    RelayWithBulkStore: "0x2fd4f3ae10608cd6192339e72d4f6a0c182dee22"

-
  call:
    getBlockchainHead:
      to: $RelayWithBulkStore
      sig: getBlockchainHead:[]:int256

-
  call:
    getLastBlockHeight:
      to: $RelayWithBulkStore
      sig: getLastBlockHeight:[]:int256

-
  call:
    getCumulativeDifficulty:
      to: $RelayWithBulkStore
      sig: getCumulativeDifficulty:[]:int256

-
  call:
    getTokenContract:
      to: $RelayWithBulkStore
      sig: getTokenContract:[]:int256
