# Deploy contracts
# -
#   set:
#     RelayWithBulkStore: "0x6f217ded6c86a57f1211f464302e6fa544045b4f"
-
  deploy:
    RelayWithBulkStore:
      contract: ../../btcBulkStoreHeaders.se
      gas: 3000000
      retry: True
      wait: True
-
  transact:
    SetInitialParent:
      gas: 150000
      to: $RelayWithBulkStore
      sig: setInitialParent:[int256,int256,int256]:int256
      data:
        - 0x000000005e3057223f82d5ebd26d6a771ed50522fe7d3428a876a073e7cdd1d5
        - 532655
        - 1
      wait: True
