# Deploy contracts
# -
#   set:
#     RelayWithBulkStore: "0x6f217ded6c86a57f1211f464302e6fa544045b4f"
-
  deploy:
    RelayWithBulkStore:
      contract: ../../btcBulkStoreHeaders.se
      gas: 3000000
      retry: True
      wait: True
-
  transact:
    SetInitialParent:
      gas: 150000
      to: $RelayWithBulkStore
      sig: setInitialParent:[int256,int256,int256]:int256
      data:
        - 0x0000000000006672235c1606fbacd7861b16b267d203b4d687708eeb1fc25e6d
        - 626975  # make sure this follows rules of SetInitialParent()
        - 1  # need to compute chainWork
      retry: 60
      wait: True
