# Deploy contracts
# -
#   set:
#     RelayWithBulkStore: "0x6f217ded6c86a57f1211f464302e6fa544045b4f"
-
  deploy:
    RelayWithBulkStore:
      contract: ../../btcBulkStoreHeaders.se
      gas: 3000000
      retry: True
      wait: True
-
  transact:
    SetInitialParent:
      gas: 150000
      to: $RelayWithBulkStore
      sig: setInitialParent:[int256,int256,int256]:int256
      data:
        - 0x0000000003857aa239ea78acfab7f429141c584ece466106126cd438bdc0ef11
        - 529948
        - 1
      wait: True
